#!/usr/bin/env python2.7
"""This script compiles sequences written in the FPE Sequencer DSL to a binary file"""

if __name__ == "__main__":
    from tessfpe.sequencer_dsl.parse import parse_file
    from tessfpe.sequencer_dsl.sequence import compile_sequences
    from tessfpe.dhu.binary_files import write_seqmem
    import sys
    import argparse

    parser = argparse.ArgumentParser(
        description='Compile the sequences from code written in the FPE Sequencer DSL to a binary file.')
    parser.add_argument('program', nargs='?', type=argparse.FileType('r'), default=sys.stdin,
                        help='''A file containing the sequencer DSL code;
                        if no file is specified then /dev/stdin is read.''')
    parser.add_argument('output_file_name', nargs='?', type=str, default=None,
                        help='''A file name for where to write the binary encoding of the sequences specified in the input;
                        if no file is specified then a random temporary file will be generated.''')
    args = parser.parse_args()

    ast = parse_file(args.program)

    print "Wrote {}".format(
        write_seqmem(compile_sequences(ast),
                     args.output_file_name))
