#!/usr/bin/env python2.7
"""This script converts an FPE program to SPICE timing"""

if __name__ == "__main__":
    from tessfpe.sequencer_dsl.sequence import compile_sequences
    from tessfpe.sequencer_dsl.parse import parse_file
    from tessfpe.sequencer_dsl.spice.timing import timing_sequence
    import argparse
    import sys
    parser = argparse.ArgumentParser(description='Convert an FPE program to spice timing')
    parser.add_argument('program', nargs='?', type=argparse.FileType('r'), default=sys.stdin, help='An file (or if not specified, stdin) containing the FPE program to convert')
    parser.add_argument('--sequence', nargs='?', help="The sequence to be printed")
    parser.add_argument('--bits', nargs='+', help="The bits to be printed")
    args = parser.parse_args()
    ast = parse_file(args.program)
    sequence_names = [s for s in ast["sequences"]]
    if len(sequence_names) == 0:
        raise Exception("No sequences found in FPE program")
    elif len(sequence_names) == 1:
        print timing_sequence(ast,sequence_names[0],args.bits)
    else:
        if args.sequence is None:
             raise Exception("Multiple sequences detected but no sequence specified")
        print timing_sequence(ast,args.sequence,args.bits)
