#!/usr/bin/env python2.7
"""This script checks if the Observatory simulator is running frames or not"""

if __name__ == "__main__":
    from tessfpe.dhu.fpe import FPE
    from tessfpe.dhu.unit_tests import check_house_keeping_voltages
    import sys
    import argparse
    parser = argparse.ArgumentParser(description='Stop running frames')
    parser.add_argument('--FPE-number', metavar='N', type=int, nargs='?', default=1, help='which FPE to use')
    args = parser.parse_args()
    
    with FPE(args.FPE_number, sanity_checks=False) as fpe:
        print fpe.cmd_stop_frames()
        sys.exit(0)  # 0 is SUCCESS for shell commands
