#!/usr/bin/env python2.7
"""This script checks if the Observatory simulator is running frames or not"""

if __name__ == "__main__":
    from tessfpe.dhu.fpe import FPE
    from tessfpe.dhu.unit_tests import check_house_keeping_voltages
    import sys
    
    # TODO: Handle exceptions?
    with FPE(1, sanity_checks=False) as fpe:
        print fpe.cmd_stop_frames()
        sys.exit(0)  # 0 is SUCCESS for shell commands
