#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""This script parses, compiles and loads an FPE sequencer DSL program to the DHU."""

if __name__ == "__main__":
    from tessfpe.dhu.fpe import FPE
    import argparse
    import sys

    # Parse the command line arguments
    parser = argparse.ArgumentParser(description='Load a FPE sequencer DSL program to the DHU')
    parser.add_argument('program', nargs='?', type=argparse.FileType('r'), default=sys.stdin, help='the FPE program to upload')
    parser.add_argument('--FPE-number', metavar='N', type=int, nargs='?', default=1, help='which FPE to use')
    parser.add_argument('--debug', action='store_true', help="print debugging information ")
    args = parser.parse_args()

    with FPE(args.FPE_number, debug=args.debug) as fpe:
         if fpe.compile_and_load_fpe_program(args.program):
             print "Loaded program from {0}".format(args.program.name)
             sys.exit(0)
    sys.exit(1)
