#!/bin/bash

set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYTHON=${DIR}/python

${PYTHON} ${DIR}/house_keeping --channels +1.8f +15 +3.3f +2.5f +1f +5 -12 --samples 100 $@
