@@comments :: ?/\/\*.*?\*\//?
@@eol_comments :: ?/\/\/.*?$/?

#include :: "Terms.ebnf"
#include :: "State_Changes.ebnf"
#include :: "Sequences.ebnf"
#include :: "Defaults.ebnf"
#include :: "Programs.ebnf"

(* Semantics for hold: Emit a program instruction to execute 
   the sequence identified  by symbol count times. The 
   instruction should have the HOLD bit set, and 
   DATA_TYPE of no_data. *)
hold = "hold" hold:symbol ;

(* Top level rule *)

readout = >defaults programs:{ ( sequence | parameter | program ) }* >hold $ ;

