(* Semantics for state_change: must be the name of a sequencer bit
   from Section 5.2.2 of the the FPGA document.
   Change the state accordingly. *)
state_changes = { state_change }* ;
state_change = bit_name ( "high" | "low" ) ;
bit_name = "P1-IA-1" | "P2-IA-1" | "P3-IA-1" | "P1-IA-2" | "P2-IA-2" |
           "P3-IA-2" | "P1-IA-3" | "P2-IA-3" | "P3-IA-3" | "P1-IA-4" |
           "P2-IA-4" | "P3-IA-4" | "P1-FS-1" | "P2-FS-1" | "P3-FS-1" |
           "P1-FS-2" | "P2-FS-2" | "P3-FS-2" | "P1-FS-3" | "P2-FS-3" |
           "P3-FS-3" | "P1-FS-4" | "P2-FS-4" | "P3-FS-4" | "P1-OR"   |
           "P2-OR"   | "P3-OR"   | "RG"      | "ID"      | "Int"     |
           "DeInt"   | "Clamp"   | "CNV"     | "P1-U"    | "P2-U"    |
           "P3-U" ;